version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true 
    tty: true 
    deploy:
      resources:
        limits:
          cpus: '2'
    volumes: 
      - ./:/home/second-order

